spring.application.name=fist-spring-app
server.port = 3001
spring.datasource.url=mysql://localhost:3306/fist-spring-app
spring.datasource.username=root
spring.datasource.password=root
spring.profile.active=dev
